### ISSUE TITLE
Upgrade project to 10.9 - JSC_OBJC_API_ENABLED /  JSExport

### ISSUE THREAD

**Issue by wildthink** [ccgus/CocoaScript#22]
Is there any reason not to upgrade to (at least) 10.9 as the project target version? I note that 10.9 is required for JSExport Protocol support. I'm just beginning to look into it but it appears there are several improvements to the bridging API with 10.9. (JSC_OBJC_API_ENABLED)

**Comment by ccgus** [comment]
CS doesn't use the JSC bridge though- so I'm not sure what good will come of it?  Unless I'm missing something…

**Comment by wildthink** [comment]
I'm still learning how CS does things but the JSC bridge (overview at http://nshipster.com/javascriptcore/) seems to improve Block to JS Functions mapping as well as the creation of bridging proxy performing akin to a ProtocolChecker.

**Comment by ccgus** [comment]
Yep, I'm aware of that stuff.  But then that also means dropping what we've done (which might be reasonable, but just setting a flag won't make that happen

**Comment by wildthink** [comment]
True. Let's close this up. we can revisit later if we want.
