### ISSUE TITLE
El Capitan  [textField setAlignment:NSCenterTextAlignment]; gives symbol not found.

### ISSUE THREAD

**Issue by maximedegreve** [ccgus/CocoaScript#31]
In the Sketch plugin when I use [textField setAlignment:NSCenterTextAlignment]; I get an error saying: Symbol not found: (null) Any idea what this could be?

**Comment by maximedegreve** [comment]
In the Sketch plugin when I use [textField setAlignment:NSCenterTextAlignment]; I get an error saying: Symbol not found: (null) Any idea what this could be?

**Comment by ccgus** [comment]
Sounds like maybe the bridging headers have changed, and CS isn't able to parse it, or find the symbol

**Comment by maximedegreve** [comment]
I guess I might have to ask the guys of Sketch!
