### ISSUE TITLE
Question: CocoaScript compatibility with ECMAScript?

### ISSUE THREAD

**Issue by nazikus** [ccgus/CocoaScript#33]
What ECMAScript Edition CocoaScript is compatible with?

My intention is to write a single javascript module that should run under different environments:
 * Phothosop (Adobe ExtendedScript, ES3)
 * Browsers (V8, Nitro, SpiderMonkey, mostly ES5.1)
 * Sketch (CocoaScript, ES?)

Also, what JavaScript engine is used for CocoaScript?
Not much technical info about CocoaScript out there, would appreciate your feedback.
Thank you

**Comment by ccgus** [comment]
Cocoa Script uses whatever version of JavaScriptCore is on the system (aka, WebKit and Safari's JS engine).
