### ISSUE TITLE
fileExistsAtPath not working

### ISSUE THREAD

**Issue by corysimmons** [ccgus/CocoaScript#37]
Can't find any documentation. Seems like an insanely simple thing to do...

```js
var fileManager = [NSFileManager defaultManager];

var fileExists = function(dir, file) {
  var filePath = dir + "/" + file;
  return [fileManager fileExistsAtPath:filePath];
};

log(fileExists("~/Desktop", "exists.md"));
log(fileExists("~/Desktop", "doesnt-exist.md"));
```

Seems like [it should work](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSFileManager_Class/#//apple_ref/occ/instm/NSFileManager/fileExistsAtPath:) but it's returning `0` for both of those.

Is there any documentation for Sketch Plugin developers or are we really just supposed to piece it all together by [looking at various projects](https://github.com/sketchplugins/plugin-directory) written in various languages (JSTalk, CocoaScript) that are combinations of various languages (JavaScript, Cocoa, Objective-C)?

Am I really the only one who thinks this is ridiculous?

**Comment by ccgus** [comment]
It isn't working, because you aren't giving it a valid path.

Try: @"~/Desktop" stringByExpandingTildeInPath]
