### ISSUE TITLE
How do you test for type in CocoaScript?

### ISSUE THREAD

**Issue by corysimmons** [ccgus/CocoaScript#38]
And how do you type cast?

**Comment by corysimmons** [comment]
For others: you can test for type with `log(typeof(myVariable));`

**Comment by ccgus** [comment]
What are you trying to do specifically? If you've got an NSObject subclass, you can use isKindOfClass:

**Comment by corysimmons** [comment]
Thanks for your answers, but I'm done with Sketch plugin development.
