### ISSUE TITLE
How to deal with many arguments

### ISSUE THREAD

**Issue by onmyway133** [ccgus/CocoaScript#41]
Hi, some methods like `- (instancetype)initWithContentRect:(NSRect)contentRect styleMask:(NSUInteger)windowStyle backing:(NSBackingStoreType)bufferingType defer:(BOOL)deferCreation` has many arguments, how to call them in cocoascript?

Thanks

**Comment by ccgus** [comment]
Check out the examples:
https://github.com/ccgus/CocoaScript/blob/master/examples/NSImage%20Draw%20Buttons.jstalk

**Comment by onmyway133** [comment]
@ccgus thanks. I see that we can use 

```js
var window = NSWindow.alloc().initWithContentRect_styleMask_backing_defer_(
      NSMakeRect(0, 0, 1365, 500), NSTitledWindowMask, NSBackingStoreBuffered, false)
```

**Comment by zschuessler** [comment]
@onmyway133 you just saved me from 90 minutes of headache, thanks for sharing what you found.

**Comment by onmyway133** [comment]
@zschuessler Hope that it helps. Btw, if you're developing Sketch plugin, read my story here https://medium.com/@onmyway133/create-sketch-plugin-b97fb919e4c4#.qzfz04c38 on switching to using Objc framework
