### ISSUE TITLE
Focusing issues on Sierra when using COSAlertWindow

### ISSUE THREAD

**Issue by bomberstudios** [ccgus/CocoaScript#45]
We've had a few reports from plugin developers about this issue. Here's an example:

> I was working on the upload of bunch new feature for my plugin
> https://github.com/vincenzopetito/Shapr
> 
> I've noticed that on Sierra when I run the shortcut and open the window I
> cannot switch between inputs as I did before on ElCapitan, plus the first
> input field is not automatically focused.

They're using `COSAlertWindow` on their code.

Another developer told us that:

> For this to work in Sierra you can explicitly define the `initialFirstResponder` for the alert window and `nextKeyView` for each NSTextField.
> 
> Here's an example:
> 
> ```
> var alert = COSAlertWindow.new();
> alert.addTextFieldWithValue("");
> alert.addTextFieldWithValue("");
> var firstField = alert.viewAtIndex(0);
> var secondField = alert.viewAtIndex(1);
> alert.alert().window().setInitialFirstResponder(firstField)
> firstField.setNextKeyView(secondField)
> alert.runModal()
> ```

Is this something that could be improved in https://github.com/ccgus/CocoaScript/blob/master/src/framework/COSAlertWindow.m?

**Comment by ccgus** [comment]
I find it works better in 10.12.1 like so:


```
var alert = COSAlertWindow.new();
alert.addTextFieldWithValue("");
alert.addTextFieldWithValue("");
alert.runModal()
```

In the example you gave me, the next key loop stops at the second field, and doesn't tab over to the OK button.

So I don't think there's anything Cocoa Script should change.

**Comment by bomberstudios** [comment]
Indeed, this seems to work as expected on 10.12.1. Closing!
