### ISSUE TITLE
Anyway to reload a framework with Mocha?

### ISSUE THREAD

**Issue by mludowise** [ccgus/CocoaScript#46]
I wrote a plugin that uses Mocha to load a custom Objective-C framework. My plugin is able to self-update but the changes in my framework aren't loaded until after Sketch is restarted.

Is there anyway to dynamically reload my framework without restarting Sketch?

**Comment by ccgus** [comment]
Are we talking about compiled code? If yes, then I don't think there's a good way to do it (maybe that's changed in the past couple of years?)

**Comment by mludowise** [comment]
Yes, it's compiled code in a .framework.

**Comment by ccgus** [comment]
I think you're out of luck, other than restarting Sketch.

**Comment by mludowise** [comment]
Yeah, that's what I figured but thought I'd ask anyway ☺️

Thank you for the speedy response!
