### ISSUE TITLE
Cannot use NSFont from Cocoa Script

### ISSUE THREAD

**Issue by jfpoole** [ccgus/CocoaScript#55]
STEPS:
* Checkout and build 
* Launch Cocoa Script Editor
* Enter the following script:
```javascript
var footerAttributes = [NSMutableDictionary dictionary];
footerAttributes[NSFontAttributeName] = [NSFont fontWithName:@"Helvetica" size:9];
```
* Click Run

BUG:
Cocoa Script Editor crashes.  The following message is displayed if running Cocoa Script Editor from the console: `Cannot form weak reference to instance (0x60400004b5e0) of class NSFont. It is possible that this object was over-released, or is in the process of deallocation.`

EXPECTED:
Cocoa Script Editor runs the script without issue.

**Comment by jfpoole** [comment]
The underlying issue seems to be that Cocoa Script (or rather Mocha?) cannot handle objects that do not support weak references.  Both MOBox and _objectsToBoxes try to store weak references to the NSFont object, which leads to the crash.

Modifying MOBox and _objectsToBoxes to store strong rather than weak references fixes the problem, but I'm not sure what issues this approach may introduce.  Is there a better solution?

**Comment by ccgus** [comment]
I'm going to cc @logancollins here, since he's the original creator of Mocha, and he might have a better understanding of why MOBox uses weak for _objectsToBoxes.

I guess in theory, it would be fine to make it strong, since there is cleanup later on. I be it's done just as a precaution against leaks.
